/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;

/**
 *
 * @author MR-BM
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    String nombre;
    
    public Inicio() {
        initComponents();
        setTitle("Linda Sonrisa");
        setLocationRelativeTo(null);
        setResizable(false);    
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombreOdontologo = new javax.swing.JLabel();
        odontologo = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        btnAgendaHoy = new javax.swing.JLabel();
        btnAgendaHoyDisa = new javax.swing.JLabel();
        btnCalendarioDisa = new javax.swing.JLabel();
        btnCalendario = new javax.swing.JLabel();
        btnHistorialM1 = new javax.swing.JLabel();
        btnHistorialM = new javax.swing.JLabel();
        btnConfiguracion = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();
        Vertical1 = new javax.swing.JLabel();
        Vertical = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        FondoMedio = new javax.swing.JLabel();
        FondoPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreOdontologo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblNombreOdontologo.setText("adadadad");
        jPanel1.add(lblNombreOdontologo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 110, 20));

        odontologo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        odontologo.setText("Odontológo");
        jPanel1.add(odontologo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 110, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 130, -1));

        btnAgendaHoy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnAgendaHoy.png"))); // NOI18N
        jPanel1.add(btnAgendaHoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 270, 60));

        btnAgendaHoyDisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnAgendaDisa.png"))); // NOI18N
        jPanel1.add(btnAgendaHoyDisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 270, 60));

        btnCalendarioDisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnCalendarioDisabled.png"))); // NOI18N
        jPanel1.add(btnCalendarioDisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 270, 60));

        btnCalendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnCalendario.png"))); // NOI18N
        jPanel1.add(btnCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 270, 60));

        btnHistorialM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnHistorialDisabled.png"))); // NOI18N
        jPanel1.add(btnHistorialM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 270, 70));

        btnHistorialM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnHistorial.png"))); // NOI18N
        jPanel1.add(btnHistorialM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 270, 50));

        btnConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuracion.png"))); // NOI18N
        jPanel1.add(btnConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 270, 60));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 270, 70));

        Vertical1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vertical.png"))); // NOI18N
        jPanel1.add(Vertical1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 640));

        Vertical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vertical.png"))); // NOI18N
        jPanel1.add(Vertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, -1, 240));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 720));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoMedio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        FondoMedio.setText("jLabel1");
        jPanel2.add(FondoMedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1000, 480));

        FondoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoCompleto.png"))); // NOI18N
        jPanel2.add(FondoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1089, 800));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 1010, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoMedio;
    private javax.swing.JLabel FondoPrincipal;
    private javax.swing.JLabel Vertical;
    private javax.swing.JLabel Vertical1;
    private javax.swing.JLabel btnAgendaHoy;
    private javax.swing.JLabel btnAgendaHoyDisa;
    private javax.swing.JLabel btnCalendario;
    private javax.swing.JLabel btnCalendarioDisa;
    private javax.swing.JLabel btnConfiguracion;
    private javax.swing.JLabel btnHistorialM;
    private javax.swing.JLabel btnHistorialM1;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNombreOdontologo;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel odontologo;
    // End of variables declaration//GEN-END:variables
}
