/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;
import procedimientos.Encryptar;

/**
 *
 * @author MR-BM
 */
public class IniciarSesion extends javax.swing.JFrame {

    /**
     * Creates new form IniciarSesion
     */
    public IniciarSesion() {
        initComponents();
        setTitle("Linda Sonrisa");
        setLocationRelativeTo(null);
        setResizable(false);    
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);            
        lblError1.setVisible(false);
        lblError2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblError2 = new javax.swing.JLabel();
        lblError1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        btnEntrar2 = new javax.swing.JButton();
        btnSalir = new javax.swing.JLabel();
        btnOlvidadoContr = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblError2.setBackground(new java.awt.Color(243, 84, 93));
        lblError2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblError2.setForeground(new java.awt.Color(243, 84, 93));
        lblError2.setText("Usuario no existe. Contáctese con el administrador.");
        lblError2.setToolTipText("");
        jPanel1.add(lblError2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, -1, -1));

        lblError1.setBackground(new java.awt.Color(243, 84, 93));
        lblError1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblError1.setForeground(new java.awt.Color(243, 84, 93));
        lblError1.setText("Hemos tenido un problema. Intente Nuevamente.");
        lblError1.setToolTipText("");
        jPanel1.add(lblError1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, -1, -1));

        txtPassword.setForeground(new java.awt.Color(119, 119, 119));
        txtPassword.setText("jPasswordField1");
        txtPassword.setBorder(null);
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 310, 30));

        txtUsername.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(119, 119, 119));
        txtUsername.setText("Ingresa tu nombre de usuario");
        txtUsername.setBorder(null);
        txtUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsernameMouseClicked(evt);
            }
        });
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 310, 30));

        btnEntrar2.setBackground(new java.awt.Color(255, 153, 153));
        btnEntrar2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnEntrar2.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar2.setBorder(null);
        btnEntrar2.setBorderPainted(false);
        btnEntrar2.setContentAreaFilled(false);
        btnEntrar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 140, 50));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        btnSalir.setText("jLabel1");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 570, 140, 40));

        btnOlvidadoContr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnOlvidadoContr, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 190, 20));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Login2.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        // TODO add your handling code here:
        txtPassword.setText("");
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsernameMouseClicked
        // TODO add your handling code here:
        txtUsername.setText("");
    }//GEN-LAST:event_txtUsernameMouseClicked

    private void btnEntrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrar2ActionPerformed
        // TODO add your handling code here:
//        String username = txtUsername.getText();
//        char[] password = txtPassword.getPassword();
//        String pass = new String(password);
//
//        lblError1.setVisible(false);
//        lblError2.setVisible(false);
        
        Inicio v = new Inicio();
        v.setVisible(true);
        this.setVisible(false);

//        try {
//            String p = Encryptar.encryptar(pass);
//            Users u = (new UsersDAO()).buscarUsername(username);
//            if(u !=null){
//                if(username.equals(u.getUsername()) & p.equals(u.getPassword())){
//                    Home v = new Home();
//                    v.nombre = u.getNombres() + " " + u.getApellidos();
//                    v.setVisible(true);
//                    this.setVisible(false);
//                }else{
//                    lblError1.setVisible(true);
//                    lblError2.setVisible(false);
//                    //                    System.out.println("Error");
//                }
//            }else{
//                lblError1.setVisible(false);
//                lblError2.setVisible(true);
//            }
//
//        } catch (NoSuchAlgorithmException ex) {
//            //            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
//            lblError1.setVisible(true);
//            lblError2.setVisible(false);
//        }

    }//GEN-LAST:event_btnEntrar2ActionPerformed

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnEntrar2;
    private javax.swing.JLabel btnOlvidadoContr;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblError1;
    private javax.swing.JLabel lblError2;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
