/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ComunaDAO;
import dao.FichaClienteDAO;
import dao.HorarioDAO;
import dao.OdontologoDAO;
import dao.RegionDAO;
import dao.ReservaHoraDAO;
import dao.ServicioDAO;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.FichaCliente;
import modelo.Odontologo;
import modelo.ReservaHora;
import procedimientos.ColorearFilas;

/**
 *
 * @author MR-BM
 */
public class Paciente extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public int id_odontologo, id_reservar_hora;
    public Odontologo odontologo;
        
    //Colores
    ColorearFilas colores = new ColorearFilas();
    
    public Paciente() {
        initComponents();
        setTitle("Linda Sonrisa");
        setLocationRelativeTo(null);
        setResizable(false);    
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
        
        this.setIconImage(new ImageIcon(getClass().getResource("/img/icono.png")).getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombreOdontologo = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        btnAgendaHoy = new javax.swing.JLabel();
        btnCalendarioDisa = new javax.swing.JLabel();
        btnHistorialM1 = new javax.swing.JLabel();
        btnConfiguracion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();
        Vertical1 = new javax.swing.JLabel();
        Vertical = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblAgenda = new javax.swing.JLabel();
        lblAgenda1 = new javax.swing.JLabel();
        homeIcon = new javax.swing.JLabel();
        cbEstadoServicio = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Titulo2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Titulo1 = new javax.swing.JLabel();
        lblNombrePaciente = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblRegion = new javax.swing.JLabel();
        lblRun = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComentario = new javax.swing.JTextArea();
        lblComuna = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Titulo3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jopcion = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JLabel();
        btnGuardaCambios = new javax.swing.JLabel();
        lblNombreServicio = new javax.swing.JLabel();
        FondoMedio2 = new javax.swing.JLabel();
        FondoMedio1 = new javax.swing.JLabel();
        FondoMedio3 = new javax.swing.JLabel();
        FondoPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreOdontologo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(lblNombreOdontologo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 160, 20));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 130, -1));

        btnAgendaHoy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnAgendaHoy.png"))); // NOI18N
        btnAgendaHoy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnAgendaHoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 270, 60));

        btnCalendarioDisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnCalendarioDisabled.png"))); // NOI18N
        btnCalendarioDisa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalendarioDisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalendarioDisaMouseClicked(evt);
            }
        });
        jPanel1.add(btnCalendarioDisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 270, 60));

        btnHistorialM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnHistorialDisabled.png"))); // NOI18N
        btnHistorialM1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistorialM1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistorialM1MouseClicked(evt);
            }
        });
        jPanel1.add(btnHistorialM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 270, 70));

        btnConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuracion.png"))); // NOI18N
        btnConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 270, 50));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Odontólogo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 140, 20));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 270, 50));

        Vertical1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vertical.png"))); // NOI18N
        jPanel1.add(Vertical1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 640));

        Vertical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vertical.png"))); // NOI18N
        jPanel1.add(Vertical, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, -1, 240));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 720));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAgenda.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblAgenda.setForeground(new java.awt.Color(68, 68, 68));
        lblAgenda.setText("Paciente");
        jPanel2.add(lblAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 100, 60, 20));

        lblAgenda1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblAgenda1.setForeground(new java.awt.Color(68, 68, 68));
        lblAgenda1.setText("Agenda Hoy");
        lblAgenda1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAgenda1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgenda1MouseClicked(evt);
            }
        });
        jPanel2.add(lblAgenda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 70, 90, 20));

        homeIcon.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        homeIcon.setForeground(new java.awt.Color(68, 68, 68));
        homeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        jPanel2.add(homeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 60, 60, 60));

        cbEstadoServicio.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cbEstadoServicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cancelado", "Pendiente", "Atendido", "No Asistió" }));
        jPanel2.add(cbEstadoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 140, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Región:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 140, 30));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Hora:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 50, 30));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Run:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 140, 30));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setText("Comuna:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 140, 30));

        jSeparator2.setForeground(new java.awt.Color(68, 68, 68));
        jSeparator2.setToolTipText("");
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 90, 100, 10));

        Titulo2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Titulo2.setForeground(new java.awt.Color(68, 68, 68));
        Titulo2.setText("Información del Paciente");
        jPanel2.add(Titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 310, 30));

        jSeparator3.setForeground(new java.awt.Color(68, 68, 68));
        jSeparator3.setToolTipText("");
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 190, 10));

        Titulo1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(68, 68, 68));
        Titulo1.setText("Formulario de atención");
        jPanel2.add(Titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 440, 60));

        lblNombrePaciente.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel2.add(lblNombrePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 210, 30));

        lblHora.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel2.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 140, 30));

        lblRegion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel2.add(lblRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 240, 30));

        lblRun.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel2.add(lblRun, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 210, 30));

        txtComentario.setColumns(20);
        txtComentario.setRows(5);
        jScrollPane1.setViewportView(txtComentario);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 420, 120));

        lblComuna.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel2.add(lblComuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 230, 30));

        lblFecha.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel2.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 140, 30));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setText("Fecha:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 50, 30));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setText("Nombre Paciente:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 140, 30));

        Titulo3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Titulo3.setForeground(new java.awt.Color(68, 68, 68));
        Titulo3.setText("Detalles Consulta");
        jPanel2.add(Titulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 200, 30));

        jSeparator4.setForeground(new java.awt.Color(68, 68, 68));
        jSeparator4.setToolTipText("");
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 190, 10));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setText("Estado del Servicio:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 140, 30));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setText("Servicio:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 70, 30));

        jopcion.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        jopcion.setText("(opcional)");
        jPanel2.add(jopcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 70, 30));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setText("Comentario:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 120, 30));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver.png"))); // NOI18N
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        jPanel2.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 580, 90, 50));

        btnGuardaCambios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar cambios.png"))); // NOI18N
        btnGuardaCambios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardaCambios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardaCambiosMouseClicked(evt);
            }
        });
        jPanel2.add(btnGuardaCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 580, 160, 50));

        lblNombreServicio.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel2.add(lblNombreServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 280, 30));

        FondoMedio2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        FondoMedio2.setText("jLabel1");
        jPanel2.add(FondoMedio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 520, 450));

        FondoMedio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        FondoMedio1.setText("jLabel1");
        jPanel2.add(FondoMedio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 420, 190));

        FondoMedio3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        FondoMedio3.setText("jLabel1");
        jPanel2.add(FondoMedio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 520, 450));

        FondoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoCompleto.png"))); // NOI18N
        jPanel2.add(FondoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1089, 800));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 1010, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        DateFormat formato = new SimpleDateFormat("dd-MM-YYYY");
      
        odontologo = (new OdontologoDAO()).buscar(id_odontologo);
        lblNombreOdontologo.setText(odontologo.getNombres() + " " + odontologo.getApellidos());
        ReservaHora r = (new ReservaHoraDAO()).buscar(id_reservar_hora);
//        Date date = new Date(r.getFecha_reserva());        
        FichaCliente cliente = (new FichaClienteDAO()).buscar(r.getId_ficha_cliente());        
        Date fecha = new Date();
        lblFecha.setText(formato.format(fecha));
        lblHora.setText((new HorarioDAO()).buscar(r.getId_horario()).getHorario());
        lblRun.setText(cliente.getRut());
        lblNombreServicio.setText((new ServicioDAO()).buscar(r.getId_servicio()).getNombre_servicio());
        lblNombrePaciente.setText(cliente.getNombreCompleto());
        lblComuna.setText((new ComunaDAO()).buscar(cliente.getId_comuna()).getNombre_comuna());
        lblRegion.setText((new RegionDAO()).buscar((new ComunaDAO()).buscar(cliente.getId_comuna()).getId_region()).getNombre_region());
        cbEstadoServicio.setSelectedIndex(r.getId_estado_reserva());
        if(r.getComentario()!=null){
            if(r.getComentario().length()>0){
                txtComentario.setText(r.getComentario());
            }
           
        }      

        
    }//GEN-LAST:event_formWindowActivated

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnGuardaCambiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardaCambiosMouseClicked
        // TODO add your handling code here:
        ReservaHora r = (new ReservaHoraDAO()).buscar(id_reservar_hora);
        
       
        r.setId_estado_reserva(cbEstadoServicio.getSelectedIndex());  
        r.setId_odontologo(id_odontologo);
        int m = 0;
        
        if(txtComentario.getText()!=null){
            if(txtComentario.getText().length()>0){
                r.setComentario(txtComentario.getText());
                m = 1;                
            }           
        }
        int estado = 0;
        if(m==1){
           estado = (new ReservaHoraDAO()).modificar(r);
        }else{
           estado = (new ReservaHoraDAO()).modificar2(r);
        }
     
        
        if(estado==1){
            JOptionPane.showMessageDialog(rootPane, "Se ha actualizado","Linda Sonrisa",JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(rootPane, "No se ha actualizado","Linda Sonrisa",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnGuardaCambiosMouseClicked

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        // TODO add your handling code here:
        Inicio i = new Inicio();
        i.id_odontologo = id_odontologo;
        i.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverMouseClicked

    private void lblAgenda1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgenda1MouseClicked
        // TODO add your handling code here:
        Inicio i = new Inicio();
        i.id_odontologo = id_odontologo;
        i.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblAgenda1MouseClicked

    private void btnCalendarioDisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalendarioDisaMouseClicked
        // TODO add your handling code here:
        Calendario i = new Calendario();
        i.id_odontologo = id_odontologo;
        i.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCalendarioDisaMouseClicked

    private void btnHistorialM1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialM1MouseClicked
        // TODO add your handling code here:
        HistorialMedico i = new HistorialMedico();
        i.id_odontologo = id_odontologo;
        i.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHistorialM1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paciente().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoMedio1;
    private javax.swing.JLabel FondoMedio2;
    private javax.swing.JLabel FondoMedio3;
    private javax.swing.JLabel FondoPrincipal;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JLabel Titulo3;
    private javax.swing.JLabel Vertical;
    private javax.swing.JLabel Vertical1;
    private javax.swing.JLabel btnAgendaHoy;
    private javax.swing.JLabel btnCalendarioDisa;
    private javax.swing.JLabel btnConfiguracion;
    private javax.swing.JLabel btnGuardaCambios;
    private javax.swing.JLabel btnHistorialM1;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel btnVolver;
    private javax.swing.JComboBox cbEstadoServicio;
    private javax.swing.JLabel homeIcon;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel jopcion;
    private javax.swing.JLabel lblAgenda;
    private javax.swing.JLabel lblAgenda1;
    private javax.swing.JLabel lblComuna;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblNombreOdontologo;
    private javax.swing.JLabel lblNombrePaciente;
    private javax.swing.JLabel lblNombreServicio;
    private javax.swing.JLabel lblRegion;
    private javax.swing.JLabel lblRun;
    private javax.swing.JLabel logo;
    private javax.swing.JTextArea txtComentario;
    // End of variables declaration//GEN-END:variables

   
}
