/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import conexion.ConectarMail;
import dao.UsersDAO;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import modelo.Users;

/**
 *
 * @author benja
 */
public class RecuperarContrasena extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public RecuperarContrasena() {
        initComponents();
        setTitle("Linda Sonrisa");
        setLocationRelativeTo(null);
        setResizable(false);    
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);  
        lblError1.setVisible(false);
        lblexito.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelVersion3 = new javax.swing.JLabel();
        jLabelVersion5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabelVersion7 = new javax.swing.JLabel();
        jLabelVersion6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtUsername = new javax.swing.JTextField();
        panelVolver = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        PanelEntrar = new javax.swing.JPanel();
        btnEntrar2 = new javax.swing.JButton();
        PanelSalir = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        lblexito = new javax.swing.JLabel();
        jLabelVersion9 = new javax.swing.JLabel();
        lblError1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setIconImages(null);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(36, 46, 68));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(89, 199, 198));

        jLabelVersion3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabelVersion3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVersion3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVersion3.setText("Sistema de Gestión");

        jLabelVersion5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabelVersion5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVersion5.setText("V1.0");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/200 200.png"))); // NOI18N

        jLabelVersion7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabelVersion7.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVersion7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVersion7.setText("Odontológica");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 121, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabelVersion5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelVersion7, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelVersion3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabelVersion3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelVersion7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabelVersion5)
                .addGap(41, 41, 41))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabelVersion6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabelVersion6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVersion6.setText("Recuperar Contraseña");
        jPanel1.add(jLabelVersion6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 232, 26));

        txtUsername.setBackground(new java.awt.Color(36, 46, 68));
        txtUsername.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setText("Ingresa tu nombre de usuario o correo");
        txtUsername.setBorder(null);
        txtUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsernameMouseClicked(evt);
            }
        });
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 230, 30));

        panelVolver.setBackground(new java.awt.Color(255, 51, 51));
        panelVolver.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolver.setBackground(new java.awt.Color(243, 84, 93));
        btnVolver.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("VOLVER");
        btnVolver.setBorder(null);
        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        panelVolver.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 40));

        jPanel1.add(panelVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 90, 40));

        PanelEntrar.setBackground(new java.awt.Color(89, 199, 198));
        PanelEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelEntrarMouseClicked(evt);
            }
        });
        PanelEntrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEntrar2.setBackground(new java.awt.Color(255, 153, 153));
        btnEntrar2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnEntrar2.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar2.setText("Enviar");
        btnEntrar2.setBorder(null);
        btnEntrar2.setBorderPainted(false);
        btnEntrar2.setContentAreaFilled(false);
        btnEntrar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEntrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrar2ActionPerformed(evt);
            }
        });
        PanelEntrar.add(btnEntrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        jPanel1.add(PanelEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 130, 40));

        PanelSalir.setBackground(new java.awt.Color(255, 51, 51));
        PanelSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(243, 84, 93));
        btnSalir.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        PanelSalir.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        jPanel1.add(PanelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 80, 30));

        lblexito.setBackground(new java.awt.Color(153, 255, 102));
        lblexito.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblexito.setForeground(new java.awt.Color(204, 255, 51));
        lblexito.setText("Se ha enviado un correo.");
        lblexito.setToolTipText("");
        jPanel1.add(lblexito, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, -1, -1));

        jLabelVersion9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabelVersion9.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVersion9.setText("USUARIO o Correo");
        jPanel1.add(jLabelVersion9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        lblError1.setBackground(new java.awt.Color(243, 84, 93));
        lblError1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblError1.setForeground(new java.awt.Color(243, 84, 93));
        lblError1.setText("Hemos tenido un problema. Intente Nuevamente.");
        lblError1.setToolTipText("");
        jPanel1.add(lblError1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsernameMouseClicked
        // TODO add your handling code here:
        txtUsername.setText("");
    }//GEN-LAST:event_txtUsernameMouseClicked

    private void btnEntrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrar2ActionPerformed
        // TODO add your handling code here:
                System.out.println("Entro envio");
                
                
        String [] abecedario = {"1","2","3","4","5","6","7","8","9","0" };
        String texto = "";
        for (int i = 0; i < 4; i++) {
            int numRandon = (int) Math.round(Math.random() * 9 ) ;
            texto += abecedario[numRandon];
        }
        
        try {
            if(txtUsername.getText().length()>0){
//                int intIndex = txtUsername.getText().toLowerCase().indexOf("@gmail.com");
                int intIndex =1 ;
                if(intIndex!=-1){
                    String correo = txtUsername.getText();
                    
                    Users u = (new UsersDAO()).buscarCorreo(correo);
                    
                    if(u != null){
                        int estado = (new UsersDAO()).actualizarCorreo(correo, texto);
                        if(estado==1){
                            String asunto = "Recuperación Contraseña";
                            String titulo = "Estimado " + u.getNombres() + " " + u.getApellidos();
                            String mensaje = "   Su USUARIO es: <strong>"+u.getUsername()+"</strong>" ;     
                            mensaje += "<br>   Su nueva con CONTRASEÑA es: <strong>"+texto+"</strong>" ;   
                            String mensajeFinal = new ConectarMail().formatoCorreoInterno(titulo, mensaje);
                            int estado2 = new ConectarMail().enviarMensaje(correo, "", "",mensajeFinal,asunto, 0);
                            lblError1.setVisible(false);
                            lblexito.setVisible(true);
                        }else{
                             lblError1.setVisible(true);
                            lblexito.setVisible(false);
                        }
                    }
                }else{
                    lblError1.setVisible(true);
                    lblexito.setVisible(false);
                }
            }
           
        } catch (Exception e) {
            lblexito.setVisible(true);
            lblError1.setVisible(false);
            System.out.println("Error envio correo " + e.toString());
        }
        
    }//GEN-LAST:event_btnEntrar2ActionPerformed

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        Login v = new Login();
        v.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void PanelEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEntrarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_PanelEntrarMouseClicked

    @Override
    public Image getIconImage() {
       Image retValue = Toolkit.getDefaultToolkit().
             getImage(ClassLoader.getSystemResource("img/200 200.png"));


       return retValue;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperarContrasena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelEntrar;
    private javax.swing.JPanel PanelSalir;
    private javax.swing.JButton btnEntrar2;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelVersion3;
    private javax.swing.JLabel jLabelVersion5;
    private javax.swing.JLabel jLabelVersion6;
    private javax.swing.JLabel jLabelVersion7;
    private javax.swing.JLabel jLabelVersion9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblError1;
    private javax.swing.JLabel lblexito;
    private javax.swing.JPanel panelVolver;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
