/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import conexion.ConectarMail;
import dao.OdontologoDAO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import modelo.Odontologo;

/**
 *
 * @author MR-BM
 */
public class Recuperar extends javax.swing.JFrame {

    /**
     * Creates new form IniciarSesion
     */
    public Recuperar() {
        initComponents();
        setTitle("Linda Sonrisa");
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
        lblError1.setVisible(false);
        lblExito.setVisible(false);
        lblError3.setVisible(false);
        
        this.setIconImage(new ImageIcon(getClass().getResource("/img/icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblExito = new javax.swing.JLabel();
        lblError1 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btnVolver = new javax.swing.JLabel();
        lblError3 = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblExito.setBackground(new java.awt.Color(243, 84, 93));
        lblExito.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblExito.setForeground(new java.awt.Color(0, 153, 0));
        lblExito.setText("Se ha enviado un correo.");
        lblExito.setToolTipText("");
        jPanel1.add(lblExito, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, -1, -1));

        lblError1.setBackground(new java.awt.Color(243, 84, 93));
        lblError1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblError1.setForeground(new java.awt.Color(243, 84, 93));
        lblError1.setText("Hemos tenido un problema. Intente Nuevamente.");
        lblError1.setToolTipText("");
        jPanel1.add(lblError1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, 20));

        txtCorreo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(119, 119, 119));
        txtCorreo.setText("Ingresa tu correo");
        txtCorreo.setBorder(null);
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCorreoMouseClicked(evt);
            }
        });
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 310, 30));

        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 80, 50));

        lblError3.setBackground(new java.awt.Color(243, 84, 93));
        lblError3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblError3.setForeground(new java.awt.Color(243, 84, 93));
        lblError3.setText("Usuario no existe. Contáctese con el administrador.");
        lblError3.setToolTipText("");
        jPanel1.add(lblError3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        btnEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnviarMouseClicked(evt);
            }
        });
        jPanel1.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 140, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/recuperar2.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMouseClicked
        // TODO add your handling code here:
        txtCorreo.setText("");
    }//GEN-LAST:event_txtCorreoMouseClicked

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        // TODO add your handling code here:
        IniciarSesion v = new IniciarSesion();
        v.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarMouseClicked
        // TODO add your handling code here:
        if (txtCorreo.getText() != null) {
            if (txtCorreo.getText().length() > 0) {
                Odontologo o = (new OdontologoDAO()).buscarCorreo(txtCorreo.getText());

                if (o != null) {

                    String[] abecedario = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "0"};
                    String texto = "";
                    for (int i = 0; i < 4; i++) {
                        int numRandon = (int) Math.round(Math.random() * 9);
                        texto += abecedario[numRandon];
                    }

                    int estado = (new OdontologoDAO()).modificar(o);
                    if (estado == 1) {
                        String asunto = "Recuperación Contraseña";
                        String titulo = "Estimado " + o.nombreCompleto();
                        String mensaje = "   Su USUARIO es: <strong>" + o.getUsername() + "</strong>";
                        mensaje += "<br>   Su nueva con CONTRASEÑA es: <strong>" + texto + "</strong>";
                        String mensajeFinal = new ConectarMail().formatoCorreoInterno(titulo, mensaje);
                        int estado2 = new ConectarMail().enviarMensaje(o.getCorreo(), "", "", mensajeFinal, asunto, 0);
                        lblError1.setVisible(false);
                        lblError3.setVisible(false);
                        lblExito.setVisible(true);
                    } else {
                        lblError1.setVisible(true);
                        lblError3.setVisible(false);                        
                        lblExito.setVisible(false);
                    }

                }else{
                    lblError1.setVisible(false);
                    lblError3.setVisible(true);                        
                    lblExito.setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_btnEnviarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recuperar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recuperar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recuperar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recuperar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recuperar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel btnEnviar;
    private javax.swing.JLabel btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblError1;
    private javax.swing.JLabel lblError3;
    private javax.swing.JLabel lblExito;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
